services:
  - type: web
    name: sleep-disorder-app
    env: python
    region: singapore
    runtime: python3
    plan: free
    autoDeploy: true

    # Install dependencies
    buildCommand: "pip install -r requirements.txt"

    startCommand: "gunicorn FRONTEND.FRONTEND.wsgi:application"


    envVars:
      - key: PYTHON_VERSION
        value: 3.11.6
      - key: DJANGO_SETTINGS_MODULE
        value: FRONTEND.settings
