services:
  - type: web
    name: sleep-disorder-app
    env: python
    region: oregon
    plan: free
    runtime: python3

    # Build from the repository root
    buildCommand: "pip install -r requirements.txt"

    # Start Django inside FRONTEND
    startCommand: "gunicorn FRONTEND.wsgi:application"

    autoDeploy: true

    envVars:
      PYTHON_VERSION: 3.11.6
      DJANGO_SETTINGS_MODULE: FRONTEND.settings
