services:
  - type: web
    name: sleep-disorder-app
    env: python
    region: singapore
    runtime: python3
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn FRONTEND.FRONTEND.wsgi:application"
    plan: free
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.6
      - key: DJANGO_SETTINGS_MODULE
        value: FRONTEND.FRONTEND.settings
