services:
  - type: web
    name: sleep-disorder-app
    env: python
    region: oregon
    plan: free
    runtime: python3

    # Render must run inside Sleep_disorder directory
    workingDirectory: .

    buildCommand: "pip install -r requirements.txt"

    startCommand: "gunicorn FRONTEND.wsgi:application"

    autoDeploy: true

    envVars:
      PYTHON_VERSION: 3.10.11
      DJANGO_SETTINGS_MODULE: FRONTEND.settings
