services:
  - type: web
    name: sleep-disorder-app
    env: python
    region: singapore
    runtime: python3
    plan: free
    autoDeploy: true

    # Install dependencies
    buildCommand: "pip install -r requirements.txt"

    # Start Gunicorn from inside FRONTEND folder
    startCommand: "gunicorn --chdir FRONTEND FRONTEND.wsgi:application --bind 0.0.0.0:$PORT"

    envVars:
      - key: PYTHON_VERSION
        value: 3.11.6
      - key: DJANGO_SETTINGS_MODULE
        value: FRONTEND.settings
